[phases.setup]
commands = ["echo 'Setup phase'"]

[phases.build]
commands = ["pip install -r anonyfiles_api/requirements.txt"]

[phases.start]
command = "uvicorn anonyfiles_api.api:app --host 0.0.0.0 --port $PORT"
