[phases.setup]
commands = []

[phases.install]
commands = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r anonyfiles_api/requirements.txt"
]

[phases.build]
commands = []

[phases.start]
command = "uvicorn anonyfiles_api.api:app --host 0.0.0.0 --port $PORT"
