replacements:
  PER:
    type: codes
    options:
      prefix: NOM
      padding: 3
  LOC:
    type: codes
    options:
      prefix: VILLE
      padding: 3
  ORG:
    type: codes
    options:
      prefix: ENTR
      padding: 3
  EMAIL:
    type: faker
  DATE:
    type: faker
  MISC:
    type: redact
    options:
      text: "[REDACTED]"
