spacy_model: fr_core_news_md

replacements:
  PER:
    type: codes
    options:
      prefix: NOM_SPACY_
      padding: 3
  LOC:
    type: placeholder
    options:
      format: "[VILLE_SPACY:{}]"
  ORG:
    type: codes
    options:
      prefix: ORG_SPACY_
      padding: 3
  DATE:
    type: faker
  EMAIL:
    type: placeholder
    options:
      format: "[EMAIL_SPACY:{}]"