[package]
name = "anonyfiles-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.6", features = [] }
tauri-build = "1.5"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }
