# anonyfiles_cli/config_default.yaml
spacy_model: fr_core_news_md

replacements:
  PER:
    type: codes
    options:
      prefix: NOM_
      padding: 3

  LOC:
    type: faker
    options:
      locale: fr_FR
      provider: address

  ORG:
    type: redact
    options:
      text: "[ENTREPRISE_ANONYME]"

  DATE:
    type: codes
    options:
      prefix: DATE_CODE_
      padding: 3

  EMAIL:
    type: faker
    options:
      locale: fr_FR
      provider: email # Cette ligne est cruciale

exclude_entities: # Cette section est cruciale
  - MISC