# anonyfiles_cli/config_default.yaml
spacy_model: fr_core_news_md # Ou le modèle que vous utilisez

replacements:
  PER:
    type: codes # Ou votre stratégie actuelle pour les personnes
    options:
      prefix: NOM_ # Exemple de préfixe
      padding: 3   # Exemple de padding

  LOC:
    type: faker    # Exemple, ou votre stratégie actuelle pour les lieux
    options:
      locale: fr_FR
      provider: address

  ORG:
    type: redact  # Exemple, ou votre stratégie actuelle pour les organisations
    options:
      text: "[ENTREPRISE_ANONYME]"

  DATE:
    type: codes
    options:
      prefix: DATE_CODE_
      padding: 3

  EMAIL:
    type: faker # Ou votre stratégie actuelle pour les emails
    # options: ...

# exclude_entities:
#   - MISC